package Miscs;

import javax.swing.*;

public class Icons {
    public static ImageIcon firstIcon = new ImageIcon("gfx/first.pvz");
    public static ImageIcon buttonIcon = new ImageIcon("gfx/button.pvz");
    public static ImageIcon mowerIcon = new ImageIcon("gfx/mower.pvz");
    public static ImageIcon plantMenuIcon = new ImageIcon("gfx/pm.pvz");
    public static ImageIcon snowBulletIcon = new ImageIcon("gfx/snowBullet.pvz");
    public static ImageIcon peaBulletIcon = new ImageIcon("gfx/bullet.pvz");
    public static ImageIcon scoreBoxIcon = new ImageIcon("gfx/score.pvz");
    public static ImageIcon pauseButtonIcon = new ImageIcon("gfx/pause.pvz");
    public static ImageIcon blackScreen = new ImageIcon("gfx/blackScreen.pvz");
    public static ImageIcon pauseMenu = new ImageIcon("gfx/pauseFrame.pvz");
    public static ImageIcon sunflowerIcon = new ImageIcon("gfx/sunflower.pvz");
    public static ImageIcon peaIcon = new ImageIcon("gfx/pea.pvz");
    public static ImageIcon frozenIcon = new ImageIcon("gfx/snowPea.pvz");
    public static ImageIcon walnutIcon = new ImageIcon("gfx/nut_1.pvz");
    public static ImageIcon cherryIcon = new ImageIcon("gfx/cherry.pvz");
    public static ImageIcon background = new ImageIcon("gfx/back.pvz");
    public static ImageIcon constantZombieIcon = new ImageIcon("gfx/zombies.pvz");
    public static ImageIcon closeDialogIcon = new ImageIcon("gfx/closeD.pvz");
    public static ImageIcon saveNExitIcon = new ImageIcon("gfx/saveNExit.pvz");
    public static ImageIcon quitGameIcon = new ImageIcon("gfx/quit.pvz");
    public static ImageIcon modeHIcon = new ImageIcon("gfx/modeH.pvz");
    public static ImageIcon modeHOffIcon = new ImageIcon("gfx/modeHOff.pvz");
    public static ImageIcon modeNOffIcon = new ImageIcon("gfx/modeNOff.pvz");
    public static ImageIcon modeNIcon = new ImageIcon("gfx/modeN.pvz");
    public static ImageIcon settingsIcon = new ImageIcon("gfx/settings.pvz");
    public static ImageIcon deckIcon = new ImageIcon("gfx/chooseSeeds.pvz");
    public static ImageIcon repeaterIcon = new ImageIcon("gfx/repeater.pvz");
    public static ImageIcon threePeaIcon = new ImageIcon("gfx/threepeater.pvz");
    public static ImageIcon gatlingIcon = new ImageIcon("gfx/gatPea.pvz");
    public static ImageIcon potatoAIcon = new ImageIcon("gfx/potato_1.pvz");
    public static ImageIcon potatoBIcon = new ImageIcon("gfx/potato_2.pvz");
    public static ImageIcon potatoCIcon = new ImageIcon("gfx/potato_3.pvz");
    public static ImageIcon okCheckMarkIcon = new ImageIcon("gfx/check.pvz");
    public static final ImageIcon snowPeaCard = new ImageIcon("gfx/cardFreeze.pvz");
    public static final ImageIcon peaShooterCard = new ImageIcon("gfx/cardPea.pvz");
    public static final ImageIcon repeaterCard = new ImageIcon("gfx/cardRepeater.pvz");
    public static final ImageIcon threePeaCard = new ImageIcon("gfx/cardThree.pvz");
    public static final ImageIcon sunflowerCard = new ImageIcon("gfx/cardSun.pvz");
    public static final ImageIcon wallCard = new ImageIcon("gfx/cardWallnut.pvz");
    public static final ImageIcon cherryCard = new ImageIcon("gfx/cardCherry.pvz");
    public static final ImageIcon tPeaCard = new ImageIcon("gfx/cardThree.pvz");
    public static final ImageIcon beetCard = new ImageIcon("gfx/cardBeet.pvz");
    public static final ImageIcon gatlingCard = new ImageIcon("gfx/cardGat.pvz");
    public static final ImageIcon potatoCard = new ImageIcon("gfx/cardPotato.pvz");
}
